Marking interfaces as [SecureContext]
WebAudio/web-midi-api pull request #192
Opened 2018-10-16 10:19 UTC by cwilso

Fixes issue #183.

2018-10-16 11:26 UTC, marcoscaceres requested changes
Just one small thing.

2018-10-16 11:26 UTC, marcoscaceres commented on index.html
> +            [SecureContext] partial interface Navigator {
Oh, this is not allowed in WebIDL. You need to put [SecureContext] directly on the requestMIDIAccess() method instead.

2018-10-16 11:29 UTC, marcoscaceres requested changes
Couple of other nits.

2018-10-16 11:29 UTC, marcoscaceres commented on index.html
>          interface MIDIMessageEvent: Event {
Nit: missing “,”

2018-10-16 11:29 UTC, marcoscaceres commented on index.html
> +        [SecureContext] [Constructor(DOMString type, optional MIDIConnectionEventInit eventInitDict)]
As above.

2018-10-17 11:16 UTC, cwilso commented on index.html
>          interface MIDIMessageEvent: Event {
done.

2018-10-17 11:18 UTC, merged