Fixes #220 - Hook requestMIDIAccess into Permissions
WebAudio/web-midi-api pull request #223
Opened 2021-10-27 22:50 UTC by miketaylr

I untangled the existing requestMIDIAccess algorithm a bit (pulling out the labelled "success" / "failure" steps) - hope that's OK. 

Still a draft, because I haven't added in any Permissions integration yet. That probably comes in step 5?

2021-10-28 02:15 UTC, marcoscaceres commented on index.html
> +              Promise &lt;MIDIAccess&gt; requestMIDIAccess(optional MidiPermissionDescriptor options = {});
Unfortunately this isn't going to work because the "name" member is required (so this would be incompatible with existing stuff).

So, we need to keep  `MIDIOptions`, but, in the requestMIDIAccess() steps, we need to convert `MIDIOptions` into a MidiPermissionDescriptor whose `name` is "midi".

2021-10-28 04:24 UTC, marcoscaceres commented on index.html
> +              When invoked the {{Navigator/requestMIDIAccess()}} method returns
This whole paragraph seems redundant... the algorithm already states all this. I wonder if we can remove it?

2021-10-28 04:25 UTC, marcoscaceres commented on index.html
> +              is otherwise approved, the vended Promise is resolved. The
Similarly, this is already in the algorithm. 

```suggestion
              not appear. The
```

2021-10-28 05:00 UTC, marcoscaceres requested changes
Good start, we definitely need to rework some of this.

2021-10-28 05:00 UTC, marcoscaceres commented on index.html
> +                    <a>Document</a>.
```suggestion
                    Let |document| be the [=current global object=]'s [=associated `Document`=].
```

2021-10-28 05:00 UTC, marcoscaceres commented on index.html
> +                </li>
```suggestion
                </li>
                <li>
                   Let |promise| be [=a new promise=].
                </li>
```

2021-10-28 05:00 UTC, marcoscaceres commented on index.html
> +                  Run the following steps [=in parallel=]:
Hmm... I think this could be simplified quite a bit... the "Allow/Deny MIDI access" seems to add a bit of indirection. 

I would do simply do (in equiv HTML):

1. Let |promise| be [=a new promise=].
1. Return |promise|.
1. Run the following steps [=in parallel=]:
3.1  Let |document| be the [=current global object=]'s [=associated `Document`=].
3.2  If  |document| is not [=allowed to use=] <a>"midi"</a>, then [=reject=] |promise| with a {{"SecurityError"}} {{DOMException}} and terminate this algorithm.
3.3. and so on...  handle the error cases.
... steps...
X.X. Let |access| be a new instance of {{MIDIAccess}}.
X.X. Finally, resolve |promise| with |MIDIAccess|.
 
Try to avoid nesting the algorithm more than two if possible. 

Also, might be good to not add the `<p>` inside the `<li>`... I know they are used in the rest of the doc, but they are not needed and make the markup unnecessarily more difficult to read/maintain.

2021-10-28 05:00 UTC, marcoscaceres commented on index.html
> +                It is possible to call {{Navigator/requestMIDIAccess()}}
I know this is a legacy thing... but this seems not great (and pretty unlikely what browsers do): We should just add a guard that if it's prompting, it immediately rejects with an InvalidStateError.

2021-10-28 05:00 UTC, marcoscaceres commented on index.html
> +        <pre class="idl exclude">
```suggestion
        <pre class="idl">
```

2021-10-28 05:00 UTC, marcoscaceres commented on index.html
> +                    Optionally, e.g. based on a previously-established user
this shouldn't be needed... the algorithm either rejects or finishes with creating the MIDI object.

2021-10-28 05:00 UTC, marcoscaceres commented on index.html
> +                    Prompt the user in a user-agent-specific manner for
This should call into our spec via: [=prompt the user to choose=], which returns the permission |state|.

2021-10-28 15:48 UTC, cwilso commented on index.html
> +                It is possible to call {{Navigator/requestMIDIAccess()}}
The concern wasn't "capture what happens if you call requestMIDIAccess while the prompt is still up" - it was "be explicit that you won't get the same MIDIAccess each time".  We could strip the phrase "this may prompt the user multiple times, so it may not be best practice", I think.  Is that the issue?

2021-10-28 19:26 UTC, marcoscaceres commented on index.html
> +                It is possible to call {{Navigator/requestMIDIAccess()}}
Yeah, that was the issue.

2023-04-06 17:24 UTC, miketaylr commented
Turns out I'm not going to finish this!

2023-04-06 17:24 UTC, closed without merging